name: Firebase Functions CI/CD

on:
  push:
    branches:
      - main # The workflow will run on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Firebase CLI globally
      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      # Step 3: Install project dependencies
      - name: Install Dependencies
        run: npm install
        working-directory: ./functions # Adjust if your Firebase functions are not in the "functions" folder

      # Step 4: Deploy Firebase Functions using the token stored in secrets
      - name: Deploy Firebase Functions
        run: firebase deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
